include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_pub_dependencies

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "build/**"
    - "lib/injection.config.dart"
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
  errors:
    missing_return: error

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    technical-debt:
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
